# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVpQ3N8lXiNr5WGp6KUjR0NpUmU7F7JB
"""

# =========================
# Sistema de Gestión de Contactos (Módulo 2)
# =========================

import unittest
# Yo importo unittest porque es una librería *estándar* de Python (viene instalada)
# y me sirve para hacer pruebas unitarias, que el enunciado pide (y para que no me fallen cosas xd).

def normalizar_telefono(telefono: str) -> str:
    t = telefono.strip().replace(" ", "").replace("-", "")
    # strip() me saca espacios al inicio/final
    # replace() me borra espacios internos y guiones (para que "+56 9-1234 5678" quede "+56912345678")

    # permitimos un + al inicio
    # Yo permito que el teléfono venga con + (por ejemplo +56...), como formato internacional.
    if t.startswith("+"):
        base = t[1:]
        if not base.isdigit():
            # Si después del + hay letras o símbolos raros, lo considero inválido.
            raise ValueError("Teléfono inválido: después de '+' deben ir solo dígitos.")
    else:
        # Si no hay +, entonces exijo que sean solo dígitos.
        if not t.isdigit():
            raise ValueError("Teléfono inválido: usa solo dígitos (y opcional '+').")

    # Yo valido largo para evitar cosas demasiado cortas o demasiado largas.
    digitos = t[1:] if t.startswith("+") else t  # cuento dígitos sin considerar el "+"
    if len(digitos) < 6 or len(digitos) > 15:
        raise ValueError("Teléfono inválido: largo debe estar entre 6 y 15 dígitos.")

    return t
def validar_correo(correo: str) -> str:
    # Esta función la uso para validar el correo de forma simple.
    c = correo.strip()
    if "@" not in c or c.startswith("@") or c.endswith("@"):

        raise ValueError("Correo inválido: debe contener '@' y texto a ambos lados.")
    return c

class Contacto:
    """Contacto con encapsulación vía atributos privados y properties."""
    # guardo atributos “privados” (_nombre, _telefono, etc.) y controlo cambios con setters.

    def __init__(self, contacto_id: int, nombre: str, telefono: str, correo: str, direccion: str):
        # Este es el constructor: se ejecuta cuando creo un Contacto.
        self._id = contacto_id  # id interno (yo no lo cambio después)

        # Ojo: aquí asigno usando properties (self.nombre, self.telefono, ...)
        # para que se apliquen las validaciones automáticamente.
        self.nombre = nombre
        self.telefono = telefono
        self.correo = correo
        self.direccion = direccion

    @property
    def id(self) -> int:
        return self._id

    @property
    def nombre(self) -> str:
        return self._nombre

    @nombre.setter
    def nombre(self, value: str) -> None:
        # Setter del nombre: aquí valido y guardo.
        v = value.strip()
        if len(v) < 2:
            # Regla simple: nombre muy corto no sirve.
            raise ValueError("Nombre inválido (muy corto).")
        self._nombre = v

    @property
    def telefono(self) -> str:
        return self._telefono

    @telefono.setter
    def telefono(self, value: str) -> None:
        self._telefono = normalizar_telefono(value)

    @property
    def correo(self) -> str:
        return self._correo

    @correo.setter
    def correo(self, value: str) -> None:
        self._correo = validar_correo(value)

    @property
    def direccion(self) -> str:
        return self._direccion

    @direccion.setter
    def direccion(self, value: str) -> None:
        v = value.strip()
        if v == "":
            raise ValueError("Dirección inválida (vacía).")
        self._direccion = v

    def to_dict(self) -> dict:
        # Yo convierto el contacto a diccionario para imprimir """""bonito""""" y/o exportar fácil.
        return {
            "id": self.id,
            "nombre": self.nombre,
            "telefono": self.telefono,
            "correo": self.correo,
            "direccion": self.direccion,
        }

    def __repr__(self) -> str:
        # Esto define cómo se “muestra” el objeto si lo imprimo en consola (útil para debug jaja).
        return f"Contacto(id={self.id}, nombre='{self.nombre}', telefono='{self.telefono}')"


class AgendaContactos:
    """
    - Lista: guarda los contactos (para listar fácilmente)
    - Dict por ID: acceso rápido por id
    - Dict por teléfono: búsqueda rápida por teléfono y regla de unicidad
    """
    def __init__(self):
        # Aquí inicializo mi “base de datos” en memoria.
        self._contactos = []           # LISTA: acá guardo los Contacto en orden
        self._por_id = {}              # DICCIONARIO: id -> Contacto
        self._por_telefono = {}        # DICCIONARIO: telefono_normalizado -> id
        self._next_id = 1              # contador para generar IDs únicos

    def agregar_contacto(self, nombre: str, telefono: str, correo: str, direccion: str) -> int:
        # Agrego un contacto nuevo y devuelvo su ID.
        tel = normalizar_telefono(telefono)
        if tel in self._por_telefono:
            # Regla: no permito dos contactos con el mismo teléfono.
            raise ValueError("Ya existe un contacto con ese teléfono.")

        cid = self._next_id      # asigno ID
        self._next_id += 1       # preparo el próximo ID

        c = Contacto(cid, nombre, tel, correo, direccion)  # creo el objeto Contacto

        # Guardo en mis tres estructuras:
        self._contactos.append(c)      # lista (para listar)
        self._por_id[cid] = c          # dict por id (para acceso rápido)
        self._por_telefono[tel] = cid  # dict por teléfono (para búsqueda/duplicados)

        return cid
    def listar_contactos(self):
        # Devuelvo una copia de la lista para no exponer la lista interna directamente.
        return list(self._contactos)

    def obtener_contacto(self, contacto_id: int) -> Contacto:
        if contacto_id not in self._por_id:
            raise KeyError("No existe un contacto con ese ID.")
        return self._por_id[contacto_id]

    def buscar_por_nombre(self, texto: str):
        q = texto.strip().lower()
        return [c for c in self._contactos if q in c.nombre.lower()]

    def buscar_por_telefono(self, telefono: str):
        tel = normalizar_telefono(telefono)
        cid = self._por_telefono.get(tel)  # get devuelve None si no existe (sin explotar)
        return self._por_id.get(cid) if cid is not None else None

    def editar_contacto(self, contacto_id: int, nombre=None, telefono=None, correo=None, direccion=None) -> None:
        # Edito campos opcionales: si alguno viene como None, lo dejo tal cual.
        c = self.obtener_contacto(contacto_id)

        # Si cambia teléfono: chequear unicidad y actualizar índice
        if telefono is not None:
            nuevo_tel = normalizar_telefono(telefono)
            # Si el nuevo teléfono ya lo tiene otro contacto, no lo permito.
            if nuevo_tel != c.telefono and nuevo_tel in self._por_telefono:
                raise ValueError("Ya existe otro contacto con ese teléfono.")

            # actualizar diccionario por teléfono
            del self._por_telefono[c.telefono]  # borro el teléfono viejo del índice
            c.telefono = nuevo_tel              # actualizo el contacto (pasa por validación)
            self._por_telefono[c.telefono] = c.id  # registro el teléfono nuevo en el índice

        # Los demás campos se actualizan solo si vienen:
        if nombre is not None:
            c.nombre = nombre
        if correo is not None:
            c.correo = correo
        if direccion is not None:
            c.direccion = direccion

    def eliminar_contacto(self, contacto_id: int) -> None:
        # Elimino un contacto por ID.
        c = self.obtener_contacto(contacto_id)

        # borrar de diccionarios (para que no quede “fantasma” en los índices)
        del self._por_id[contacto_id]
        del self._por_telefono[c.telefono]

        # borrar de la lista (búsqueda lineal simple)
        for i, item in enumerate(self._contactos):
            if item.id == contacto_id:
                self._contactos.pop(i)  # elimino por índice
                break


# ====== Menú de consola ======
def ejecutar_menu():
    # Este menú es el “prototipo funcional”: lo uso para interactuar y demostrar el sistema en vivo.
    agenda = AgendaContactos()

    while True:
        # Yo uso while True para que el menú se repita hasta que yo elija salir (modo infinito xd).
        print("\n=== Agenda de Contactos ===")
        print("1) Agregar")
        print("2) Listar")
        print("3) Buscar por nombre")
        print("4) Buscar por teléfono")
        print("5) Editar")
        print("6) Eliminar")
        print("0) Salir")

        op = input("Opción: ").strip()

        try:
            # Yo uso try/except para que si el usuario se equivoca (dato malo o ID inexistente),
            # el programa no se caiga: solo muestro el error y sigo.
            if op == "1":
                nombre = input("Nombre: ")
                telefono = input("Teléfono: ")
                correo = input("Correo: ")
                direccion = input("Dirección: ")
                cid = agenda.agregar_contacto(nombre, telefono, correo, direccion)
                print(f"✅ Agregado con ID {cid}")

            elif op == "2":
                contactos = agenda.listar_contactos()
                if not contactos:
                    print("No hay contactos.")
                for c in contactos:
                    print(c.to_dict())  # imprimo en formato diccionario para que se vea ordenado

            elif op == "3":
                q = input("Texto del nombre: ")
                res = agenda.buscar_por_nombre(q)
                print(f"Resultados: {len(res)}")
                for c in res:
                    print(c.to_dict())

            elif op == "4":
                t = input("Teléfono exacto: ")
                c = agenda.buscar_por_telefono(t)
                print(c.to_dict() if c else "Sin resultados.")

            elif op == "5":
                cid = int(input("ID a editar: "))
                c = agenda.obtener_contacto(cid)

                print("Deja vacío para mantener.")
                # Si el usuario deja vacío, uso "or None" para que quede como None y así no edito ese campo.
                nombre = input(f"Nombre [{c.nombre}]: ").strip() or None
                telefono = input(f"Teléfono [{c.telefono}]: ").strip() or None
                correo = input(f"Correo [{c.correo}]: ").strip() or None
                direccion = input(f"Dirección [{c.direccion}]: ").strip() or None

                agenda.editar_contacto(cid, nombre=nombre, telefono=telefono, correo=correo, direccion=direccion)
                print("✅ Editado.")

            elif op == "6":
                cid = int(input("ID a eliminar: "))
                agenda.eliminar_contacto(cid)
                print("🗑️ Eliminado.")

            elif op == "0":
                print("Chao 👋 ...")
                break

            else:
                print("Opción inválida...")

        except (ValueError, KeyError) as e:
            # ValueError: datos inválidos (correo/teléfono/nombre)
            # KeyError: ID inexistente
            print(f"❌ Error: {e}")


# ====== Pruebas unitarias mínimas (agregar + buscar) ======
class TestAgendaContactos(unittest.TestCase):
    # Esta clase de tests la uso para demostrar automáticamente que el sistema funciona:
    # yo pruebo agregar y buscar (que son requisitos mínimos).

    def setUp(self):
        # setUp se ejecuta antes de cada test: me deja una agenda “limpia” siempre.
        self.agenda = AgendaContactos()

    def test_agregar_contacto(self):
        # Test: agrego un contacto y verifico que el ID y el tamaño queden bien.
        cid = self.agenda.agregar_contacto(
            "Yoseph Barrera", "+56912345678", "yoseph@mail.com", "Santiago"
        )
        self.assertEqual(cid, 1)
        self.assertEqual(len(self.agenda.listar_contactos()), 1)

    def test_buscar_por_nombre(self):
        # Test: busco por nombre (substring) y espero 1 resultado.
        self.agenda.agregar_contacto("Valenthina Perez", "+56911111111", "vale@mail.com", "Providencia")
        res = self.agenda.buscar_por_nombre("valen")
        self.assertEqual(len(res), 1)

    def test_buscar_por_telefono(self):
        self.agenda.agregar_contacto("Ana", "+56922222222", "ana@mail.com", "X")
        c = self.agenda.buscar_por_telefono("+56922222222")
        self.assertIsNotNone(c)
        self.assertEqual(c.nombre, "Ana")

# 1) Para correr los tests:
#    unittest.main(argv=[''], exit=False)
#
# 2) Para usar el menú interactivo:
#    ejecutar_menu()